global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'data-collector'
    static_configs:
      - targets: ['data-collector:8001']

  - job_name: 'anomaly-detector'
    static_configs:
      - targets: ['anomaly-detector:8002']