apiVersion: v1
kind: Service
metadata:
  name: {{ include "marketpulse.fullname" . }}-api
  labels:
    app: marketpulse
    component: api
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.api.port }}
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: marketpulse
    component: api